#version: "3"
services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"  # Passive mode range
    environment:
      - FTP_USER=parsltests
      - FTP_PASS=dodosaga1234.
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    volumes:
      - ./ftp_data:/home/vsftpd

  http:
    image: httpd:alpine
    container_name: http_server
    ports:
      - "8080:80"
    volumes:
      - ./shared_data:/usr/local/apache2/htdocs:ro